set -g mode-keys vi
set -g status-keys vi
set -g renumber-windows on
set -g mouse off
set -g prefix C-x
unbind C-b
bind C-x send-prefix

set -g status-style 'bg=#696969'
set -g window-status-current-style 'bold bg=cyan' #bg=#a3a3a3'
set -g pane-border-lines simple
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=cyan'
