set -g mode-keys vi
set -g status-keys vi
set -g renumber-windows on
set -g mouse off
set -g prefix C-x
unbind C-b
bind C-x send-prefix

set -g status-style 'bg=cyan'
set -g window-status-current-style 'bold'
